added category spent changing after multibuy
fractal-academy/expenses-app pull request #110
Opened 2021-02-20 13:10 UTC by 5P4C3GR33D

2021-02-20 16:44 UTC, olenashevchuk commented on src/app/domains/Cart/components/table/CartTable.template.js
> +    const products = await Promise.allSettled(
It seems, you don`t need to use a word "await", if you use "then" after

2021-02-21 08:11 UTC, GingerBoy14 requested changes

2021-02-21 08:11 UTC, GingerBoy14 commented on src/app/domains/Cart/components/table/CartTable.template.js
> +    ).then((responce) => responce.map(({ value }) => value))
Use or `await`, or `then`, better `await` =)

2021-02-22 16:04 UTC, okrdima approved these changes

2021-02-22 16:09 UTC, sashka2131 approved these changes

2021-02-22 16:11 UTC, merged