fix conditions in logger description for Cart, Product and improved L…
fractal-academy/expenses-app pull request #123
Opened 2021-02-23 16:15 UTC by sashka2131

…og view

2021-02-23 19:05 UTC, GingerBoy14 requested changes

2021-02-23 19:05 UTC, GingerBoy14 commented on src/app/domains/Cart/components/table/CartTable.template.js
> +        console.log(item)
Delete console.log

2021-02-24 09:03 UTC, olenashevchuk approved these changes

2021-02-24 09:11 UTC, okrdima approved these changes

2021-02-24 09:11 UTC, merged