add Warning type to message,add function for determine valid date
fractal-academy/expenses-app pull request #124
Opened 2021-02-23 16:23 UTC by okrdima

2021-02-23 19:03 UTC, GingerBoy14 requested changes

2021-02-23 19:03 UTC, GingerBoy14 commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +        payload: 'Product can not move to cart'
Write or can't or can not (same style everywhere)

2021-02-23 19:25 UTC, GingerBoy14 requested changes

2021-02-23 19:25 UTC, GingerBoy14 commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +        categoryIs = true
What the purpose of using `categoryIs` var, but don't to enter messageDispatch right here

2021-02-23 19:58 UTC, 5P4C3GR33D commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +      let categoryIs = false
Wrong naming.
Not 'categoryIs', but 'isCategory'. C:

2021-02-23 20:27 UTC, 5P4C3GR33D commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +      let categoryIs = false
Or even `hasCategory`.

2021-02-24 09:10 UTC, olenashevchuk approved these changes

2021-02-24 09:11 UTC, merged