added fixed role
fractal-academy/expenses-app pull request #17
Opened 2021-01-20 09:15 UTC by AlexFry123

2021-01-26 10:52 UTC, alexpassss requested changes

2021-01-26 10:52 UTC, alexpassss commented on src/app/constants/index.js
> +>>>>>>> add98a8cf972cabb3f279e7ec17250ce38d90d3f
merge conflict

2021-01-26 10:52 UTC, alexpassss commented on src/app/domains/Role/components/views/RoleSimpleView/RoleSimpleView.template.js
> +  const [currentRole, setCurrentRole] = useState(role)
fix everything from other pull requests first

2021-01-27 20:34 UTC, GingerBoy14 requested changes

2021-01-27 20:34 UTC, GingerBoy14 commented on src/app/domains/Priority/components/select/PrioritySingleSelect/Select.style.js
> +export default styleSelect
Why there is different style declaration from RoleSingleSelect.style.js file?

2021-01-27 20:34 UTC, GingerBoy14 commented on src/app/domains/Role/components/select/RoleSingleSelect/RoleSingleSelect.styles.js
> +})
Read previous comment

2021-01-27 20:34 UTC, GingerBoy14 commented on src/app/domains/Role/components/views/RoleSimpleView/RoleSimpleView.template.js
>  RoleSimpleView.defaultProps = {}
You can remove defaultProps

2021-01-28 10:53 UTC, olenashevchuk commented on src/app/constants/role.js
> +export { ROLES }
export default should be here

2021-01-28 11:19 UTC, GingerBoy14 approved these changes

2021-01-28 11:21 UTC, olenashevchuk approved these changes

2021-01-28 11:34 UTC, sashka2131 approved these changes
ales good

2021-01-28 11:35 UTC, merged