Connect routes
fractal-academy/expenses-app pull request #26
Opened 2021-01-25 10:33 UTC by GingerBoy14

2021-01-25 20:25 UTC, alexpassss requested changes

2021-01-25 20:25 UTC, alexpassss commented on public/index.html
> +    <style>
Move to the stylesheets 
Add scss modules to the project

2021-01-25 20:25 UTC, alexpassss commented on src/app/constants/collection.js
> +  NOTIFICATION: 'notification'
Why not notificationS?

2021-01-25 20:25 UTC, alexpassss commented on src/app/constants/collection.js
> +  CART: 'cart',
Use plural for for collection names

2021-01-25 20:25 UTC, alexpassss commented on src/app/constants/collection.js
> +export { collection }
Use default export

2021-01-25 20:25 UTC, alexpassss commented on src/app/constants/routePaths.js
> +  MEMBER_SHOW: '/member/:id',
members/:id

2021-01-25 20:25 UTC, alexpassss commented on src/app/constants/routePaths.js
> +  MEMBER_EDIT: '/member/:id/edit',
Same here

2021-01-25 20:25 UTC, alexpassss commented on src/app/constants/routePaths.js
> +export { ROUTES_PATHS }
Default export

2021-01-28 07:33 UTC, okrdima approved these changes

2021-01-28 07:51 UTC, merged