Qonsoll grid session component
fractal-academy/expenses-app pull request #29
Opened 2021-01-25 14:24 UTC by AlexFry123

2021-01-26 10:52 UTC, alexpassss requested changes

2021-01-26 10:52 UTC, alexpassss commented on src/app/domains/Session/components/views/SessionSimpleView/SessionSimpleView.template.js
> +const useStyles = makeStyles({
move to the separate file

2021-01-26 10:52 UTC, alexpassss commented on src/app/domains/Session/components/views/SessionSimpleView/SessionSimpleView.template.js
> +        <Row h="center" mb={1}>
row inside row = incorrect

2021-01-26 10:52 UTC, alexpassss commented on src/app/domains/Session/components/views/SessionSimpleView/SessionSimpleView.template.js
> +        <Row h="center" my={4}>
useless properties

2021-01-26 10:52 UTC, alexpassss commented on src/app/domains/Session/components/views/SessionSimpleView/SessionSimpleView.template.js
> +          <Col cw={[11]}>
cw="11"

why 11?

2021-01-28 15:05 UTC, alexpassss requested changes

2021-01-28 15:05 UTC, alexpassss commented on src/app/domains/Session/components/views/SessionSimpleView/SessionSimpleView.template.js
> +            <Typography variant="subtitle2" className={classes.root}>
use <Typography align="center"> instead of classes.root

2021-01-28 16:10 UTC, okrdima approved these changes

2021-02-04 10:46 UTC, closed without merging