Dropdown sasha g
fractal-academy/expenses-app pull request #31
Opened 2021-01-25 20:09 UTC by aleksandrgolyk

Added Dropdown and tested in Header/Layout
![image](https://user-images.githubusercontent.com/17427921/105760036-dda15d00-5f59-11eb-9251-03929bc4c169.png)
![image](https://user-images.githubusercontent.com/17427921/105760065-e8f48880-5f59-11eb-92a1-e00e5cbbb0e8.png)
![image](https://user-images.githubusercontent.com/17427921/105760111-f4e04a80-5f59-11eb-8e44-868560b8b13a.png)

2021-01-25 20:24 UTC, alexpassss requested changes

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Dropdown/Dropdown.template.js
> +      {React.cloneElement(children, { onClick: handleMenu })}
handleMenu what? Issue with naming. Please discuss naming conventions with others

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Dropdown/Dropdown.template.js
> +        id="menu-appbar"
Id should be static

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Dropdown/Dropdown.template.js
> +          vertical: 'top',
These properties should be configurable

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Dropdown/Dropdown.template.js
> +          vertical: 'top',
Same here

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Header/Header.template.js
> +const useStyles = makeStyles((theme) => ({
Please, move to the separate file

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Header/Header.template.js
> +const DropdownList = (
Please, move code below to the separate file

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Header/Header.template.js
> +    <AppBar position="fixed" color="inherit">
Move styles to the separate file

2021-01-25 20:24 UTC, alexpassss commented on src/app/components/Navbar/Navbar.template.js
> +const useStyles = makeStyles((theme) => ({
Same issue with styles here

2021-01-28 10:57 UTC, GingerBoy14 requested changes

2021-01-28 10:57 UTC, GingerBoy14 commented on src/app/components/Dropdown/Dropdown.style.js
> +})
What the point of empty styles?

2021-01-28 10:57 UTC, GingerBoy14 commented on src/app/components/Navbar/Navbar.template.js
> +// const classes = makeStyles(styles)
remove comment

2021-01-28 14:02 UTC, okrdima approved these changes

2021-01-28 14:06 UTC, GingerBoy14 approved these changes

2021-01-28 15:00 UTC, olenashevchuk approved these changes

2021-01-28 15:01 UTC, merged