update some props in Modal window
fractal-academy/expenses-app pull request #34
Opened 2021-01-26 14:42 UTC by sashka2131

2021-01-27 20:11 UTC, GingerBoy14 requested changes

2021-01-27 20:11 UTC, GingerBoy14 commented on src/app/components/Lib/Modal/Modal.template.js
> +    typographyProps,
Maybe, it will be better to call this prop more semantic, something like `titleProps` =)

2021-01-27 20:11 UTC, GingerBoy14 commented on src/app/components/Lib/Modal/Modal.template.js
> +        <Typography {...typographyProps}>{title}</Typography>
Read previous comment

2021-01-27 20:11 UTC, GingerBoy14 commented on src/app/components/Lib/Modal/Modal.template.js
> +  buttonCancelProps: PropTypes.object.isRequired
Are this props really required?

2021-01-27 20:11 UTC, GingerBoy14 commented on src/app/components/Lib/Modal/Modal.stories.js
> +        ' can get all the Material-UI Button props and custom property "text" to set Button text'
you can use template string(backticks) for multiline comments

2021-01-28 10:52 UTC, sashka2131 commented on src/app/components/Lib/Modal/Modal.template.js
> +  buttonCancelProps: PropTypes.object.isRequired
Yup, because this props must include onClick property for action buttons in modal window, more details with description of all props in .stories.js

2021-01-28 11:43 UTC, GingerBoy14 approved these changes

2021-01-28 15:12 UTC, okrdima approved these changes

2021-01-28 21:16 UTC, olenashevchuk approved these changes

2021-02-04 10:48 UTC, closed without merging