Table and toolbar components
fractal-academy/expenses-app pull request #37
Opened 2021-01-26 19:07 UTC by 5P4C3GR33D

2021-01-26 19:45 UTC, alexpassss requested changes

2021-01-26 19:45 UTC, alexpassss commented on .vscode/settings.json
> +{
Add this file to the .gitignore

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Table/TableHead.template.js
> +const ROUTS = {
Mistake. ROUTES

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Table/TableHead.template.js
> +const useStyles = makeStyles({
Move to the separate file

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Table/TableHead.template.js
> +  cart: 'CART',
Seems to be a useless object or incorrect interpretation

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Table/TableHead.template.js
> +import { tableCells } from 'app/constants'
camelCase to UPPER_CASE

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Table/TableHead.template.js
> +    <Container display="box">
Useless display property

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Table/TableHead.template.js
> +  page: PropTypes.oneOf(['WISHES', 'CART'])
Array to constants

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Toolbar/Toolbar.template.js
> +    <Container display="box">
Useless display property

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Toolbar/Toolbar.template.js
> +            {props.numberChecked > 0 ? (
numberChecked > 0 means that value should be 1, 2 or higher

1 == true

Useless comparison

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Toolbar/Toolbar.template.js
> +                      {props.numberChecked + ' selected'}
Calculate values separately from template section. Use multiline string

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Toolbar/Toolbar.template.js
> +Tolbar.propTypes = {
Mistake. Toolbar

2021-01-26 19:45 UTC, alexpassss commented on src/app/components/Lib/Toolbar/Toolbar.template.js
> +Tolbar.defaultProps = {}
Remove defaultProps

2021-01-26 19:45 UTC, alexpassss commented on src/app/domains/Cart/components/index.js
> +export { CartTable }
use default export

2021-01-26 19:45 UTC, alexpassss commented on src/app/domains/Cart/components/table/CartTable.template.js
> +const useStyles = makeStyles({
Move styles to the separate file

2021-01-29 14:31 UTC, VladBogach commented on src/app/domains/Wish/components/table/Wish.template.js
> +          <DataGrid collection="wishes" setNumSelected={setNumSelected} />
create constants for collection names

2021-01-29 14:32 UTC, VladBogach commented on src/app/domains/Cart/components/table/Cart.template.js
> +          <DataGrid collection="cart" setNumSelected={setNumSelected} />
create constants for collections names

2021-01-29 14:34 UTC, VladBogach commented on src/app/components/Lib/Toolbar/Toolbar.template.js
> +                      {`${props.numSelected} selected`}
move to separate variable

2021-01-29 14:35 UTC, VladBogach commented on src/app/components/Lib/DataGrid/DataGrid.template.js
> +    props.collection === 'cart'
create constants for collections names

2021-01-29 14:41 UTC, VladBogach commented on src/app/domains/Cart/components/table/Cart.template.js
> +  number: PropTypes.number.isRequired
check this field

2021-02-04 11:01 UTC, closed without merging