Member form generator max
fractal-academy/expenses-app pull request #38
Opened 2021-01-27 10:50 UTC by GingerBoy14

I also have changes from Lena's branch - member

2021-01-27 14:05 UTC, ARTfun00 requested changes

2021-01-27 14:05 UTC, ARTfun00 commented on src/app/domains/Member/components/select/MemberSingleSelect/MemberSingleSelect.template.js
> +      .then((snapshot) => snapshot.forEach((doc) => tmpdata.push(doc.data())))
1. It's better to place tmpdata variable in the scope of promise callback (inside .then)
2. It's better to have more semantic name for this variable
3. Please check Array.map() method and refactor code here =)

2021-01-27 14:05 UTC, ARTfun00 commented on src/app/domains/Member/components/views/MemberSimpleView/MemberSimpleView.template.js
> +  avatarUrl: PropTypes.string,
Check code line #11 =)

2021-01-27 14:05 UTC, ARTfun00 commented on src/app/services/getMembersForSelectComponent.js
> +  const snapshot = await db.collection('users').get()
same here... (check comment with collection names)

2021-01-28 15:02 UTC, alexpassss requested changes

2021-01-28 15:02 UTC, alexpassss commented on src/app/domains/Color/components/views/ColorSimpleView/ColorSimpleView.template.js
> +import { COLORS } from 'app/constants'
regroup imports

2021-01-28 15:02 UTC, alexpassss commented on src/app/domains/Member/components/combined/MemberCombined/MemberCombined.template.js
> +    STORE.collection('users')
create universal methods

2021-01-28 15:02 UTC, alexpassss commented on src/app/domains/Member/components/combined/MemberCombined/MemberCombined.template.js
> +          <form onSubmit={handleSubmit(onSubmit)}>
move form to the separate component

2021-01-28 15:13 UTC, GingerBoy14 commented on src/app/domains/Member/components/combined/MemberCombined/MemberCombined.template.js
> +    STORE.collection('users')
That will be fix when we create separate services

2021-02-04 11:01 UTC, closed without merging