Create measures components such as Form, Select, Simple View, combined component ModalWithForm
fractal-academy/expenses-app pull request #39
Opened 2021-01-27 13:14 UTC by sashka2131

2021-01-27 13:27 UTC, ARTfun00 requested changes

2021-01-27 13:27 UTC, ARTfun00 commented on src/app/domains/Measure/components/combined/MeasureModalWithForm/MeasureModalWithForm.template.js
> +    console.log(measure)
Please, remove unnecessary logs

2021-01-27 13:27 UTC, ARTfun00 commented on src/app/domains/Measure/components/select/MeasureSingleSelect/MeasureSingleSelect.template.js
> +  const MEASURES = ['кг', 'г', 'л', 'мм', 'см', 'м']
Are u sure that we will use Russian language for measure variants ?)
Please, move this variable at least outside of the component scope...
Ideally, it should be in the separate singe file with constants for the app or module...

2021-01-28 10:50 UTC, GingerBoy14 requested changes

2021-01-28 10:50 UTC, GingerBoy14 commented on src/app/constants/firebaseConfig.js
> +import 'firebase/firestore'
we will have separate firebase imports in services

2021-01-28 10:50 UTC, GingerBoy14 commented on src/app/domains/Measure/components/select/MeasureSingleSelect/MeasureSingleSelect.template.js
>  }
You can refactor this with new Select component

2021-02-04 11:02 UTC, closed without merging