add MeasureSinglSelectWithCreate fix measurSelect fix memberSelect and add ProductAdvancedForm
fractal-academy/expenses-app pull request #47
Opened 2021-02-02 20:55 UTC by okrdima

…d add ProductAdvancedForm, add REgularProductSingleSelect

2021-02-02 21:02 UTC, GingerBoy14 requested changes

2021-02-02 21:02 UTC, GingerBoy14 commented on src/app/domains/RegularProduct/components/select/RegularProductSingleSelect/RegularProductSingleSelect.template.js
If you want to use it in FormGenerator, you should pass `props` down to Select component

2021-02-02 21:06 UTC, olenashevchuk commented on src/app/domains/Category/components/select/CategorySelectWithCreate/CategorySelectWithCreate.template.js
>    return (
where is the component Сontainer?

2021-02-02 21:08 UTC, okrdima commented on src/app/domains/Category/components/select/CategorySelectWithCreate/CategorySelectWithCreate.template.js
>    return (
why i need to use container for this component?

2021-02-02 21:18 UTC, olenashevchuk commented on src/app/domains/Category/components/select/CategorySelectWithCreate/CategorySelectWithCreate.template.js
>    return (
you need to use Container, because Oleksiy said about it.  especially you use Row and Col, I think it need a wrapper

2021-02-02 21:54 UTC, olenashevchuk approved these changes

2021-02-03 06:32 UTC, GingerBoy14 approved these changes

2021-02-03 06:32 UTC, merged