Product and regular product form in modal
fractal-academy/expenses-app pull request #48
Opened 2021-02-03 09:20 UTC by AlexFry123

2021-02-03 10:07 UTC, okrdima commented on src/app/domains/Product/components/combined/ProductCombinedForm/ProductCombinedForm.template.js
> +import { RegularProductSimpleForm } from '../../../../RegularProduct/components/forms/RegularProductSimpleForm'
fix import

2021-02-03 10:07 UTC, okrdima commented on src/app/domains/Product/components/combined/ProductCombinedForm/ProductCombinedForm.template.js
> +import { ProductSimpleForm } from '../../forms/ProductSimpleForm'
fix import

2021-02-03 10:07 UTC, okrdima commented on src/app/domains/RegularProduct/components/forms/RegularProductSimpleForm/RegularProductSimpleForm.template.js
> +import RegularProductSimpleSelect from '../../select/RegularProductSingleSelect/RegularProductSingleSelect.template'
fix import

2021-02-03 13:44 UTC, GingerBoy14 requested changes

2021-02-03 13:44 UTC, GingerBoy14 commented on src/app/domains/RegularProduct/components/forms/RegularProductSimpleForm/RegularProductSimpleForm.template.js
> +import RegularProductSingleSelect from 'app/domains/RegularProduct/components/select/RegularProductSingleSelect'
fix import

2021-02-03 13:44 UTC, GingerBoy14 commented on src/app/domains/Product/components/forms/ProductSimpleForm/ProductSimpleForm.template.js
> +      <FormGenerator config={config} show={show} />
How to pass `show` property to this form?

2021-02-03 13:44 UTC, GingerBoy14 commented on src/app/domains/Product/components/combined/ProductCombinedForm/ProductCombinedForm.template.js
> +import { Typography } from '@material-ui/core'
Use one m-ui import `.../core` instead 3, fix another imports

2021-02-03 13:44 UTC, GingerBoy14 commented on src/app/domains/RegularProduct/components/forms/RegularProductSimpleForm/RegularProductSimpleForm.template.js
> +  )
How to pass `show` property to this form?

2021-02-04 10:47 UTC, sashka2131 commented on src/app/domains/Product/components/combined/ProductCombinedForm/ProductCombinedForm.template.js
> +import { Modal } from 'app/components/Lib/Modal'
Enough to use only 'app/components/Lib ' there main index wich export this component

2021-02-04 11:03 UTC, sashka2131 approved these changes

2021-02-04 11:13 UTC, GingerBoy14 approved these changes

2021-02-04 11:13 UTC, merged