Notifications with db
fractal-academy/expenses-app pull request #69
Opened 2021-02-10 15:39 UTC by AlexFry123

2021-02-10 16:23 UTC, GingerBoy14 requested changes

2021-02-10 16:23 UTC, GingerBoy14 commented on src/app/domains/Notification/components/list/NotificationList/NotificationList.template.js
> +    getData('users', md5(session.email)).then((result) => {
Use COLLECTIONS.USERS

2021-02-10 16:23 UTC, GingerBoy14 commented on src/app/domains/Notification/components/views/NotificationSimpleView/NotificationSimpleView.template.js
>    )
Use can use getCollectionRef instead firestore.collection()

2021-02-10 16:23 UTC, GingerBoy14 commented on src/app/domains/Notification/components/list/NotificationList/NotificationList.template.js
> +      .where('userId', '==', md5(session.email))
Same here

2021-02-10 16:24 UTC, okrdima commented on src/app/domains/Notification/components/list/NotificationList/NotificationList.template.js
>  import { NotificationAdvancedView } from '../../views/NotificationAdvancedView'
fix import

2021-02-10 16:24 UTC, okrdima commented on src/app/domains/Notification/components/list/NotificationList/NotificationList.template.js
>  //TODO delete mock data
delete comment

2021-02-11 13:47 UTC, okrdima approved these changes

2021-02-11 13:55 UTC, 5P4C3GR33D commented on src/app/components/Header/Header.template.js
>    let history = useHistory()
It should be 'const history', because it's not changeable variable, but it's not necessary.

2021-02-11 13:55 UTC, 5P4C3GR33D approved these changes

2021-02-11 13:56 UTC, GingerBoy14 approved these changes

2021-02-11 13:56 UTC, merged