Table fixes
fractal-academy/expenses-app pull request #72
Opened 2021-02-10 20:18 UTC by 5P4C3GR33D

2021-02-10 20:39 UTC, olenashevchuk commented on src/app/domains/Cart/routes/CartAll/CartAll.layout.js
> +    <Container>
I think, you don`t need this Container.  withLayout Component is the parent for your CartAll, and it has an own Container

2021-02-10 20:39 UTC, olenashevchuk commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +          <Typography>{moment(props.reminderDate).format('MMM Do')}</Typography>
to do calculations better no in Component

2021-02-10 20:58 UTC, GingerBoy14 requested changes

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/components/Lib/Table/Table.template.js
> +                        onClick={() => history.push(ROUTES_PATHS.MEMBER_SHOW)}>
It'll broke when i finish member, you should go to member show using his id, link `${ROUTES_PATHS.MEMBERS_ALL}/{memberId}`

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/components/Lib/Table/Table.template.js
> +    productPath: ROUTES_PATHS.REGULAR_PRODUCT_SHOW
...Path also later should "build" the same principle like member show

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/domains/Cart/components/combined/CartCombined.template.js
> +  const form = useForm({})
U don't need to pass `{}` to useForm hook

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/domains/Cart/routes/CartAll/CartAll.layout.js
> +    <Container>
Yep, use <></> instead

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +  const history = useHistory()
In react-router-dom they say that `history` is mutable soo... I don't is that correct to init `const` not `let`

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/domains/Purchase/components/list/PurchaseList/PurchaseList.template.js
> +          <Box mb={3} onClick={() => history.push(ROUTES_PATHS.PURCHASE_SHOW)}>
Same route rule as for user

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/domains/Purchase/components/views/PurchaseAdvancedView/PurchaseAdvancedView.template.js
> +  // }
Remove comments, if it's not necessary

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/domains/Wish/components/combined/WishCombined.template.js
> +  const form = useForm({})
Read previous comment for the same situation

2021-02-10 20:58 UTC, GingerBoy14 commented on src/app/domains/Wish/routes/WishAll/WishAll.layout.js
> +    <Container>
Same as in CartAll

2021-02-11 11:36 UTC, AlexFry123 approved these changes

2021-02-11 13:37 UTC, okrdima approved these changes

2021-02-11 13:54 UTC, GingerBoy14 approved these changes

2021-02-11 13:54 UTC, merged