to buy one product
fractal-academy/expenses-app pull request #93
Opened 2021-02-16 21:31 UTC by olenashevchuk

2021-02-16 22:47 UTC, GingerBoy14 requested changes

2021-02-16 22:47 UTC, GingerBoy14 commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +      await deleteData(COLLECTIONS.CART, id).then(() => history.goBack())
Use or `await`, or `then`(await - better, just move history push from then under await call)

2021-02-16 22:47 UTC, GingerBoy14 commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
>        )}
When u move product from wish to cart u'll also need to select the wallet?

2021-02-16 22:47 UTC, GingerBoy14 commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +        : (status = false)
Can u try this one: status = `data.hasOwnProperty(field) && data[field] && status ? true : false`?

2021-02-17 07:56 UTC, GingerBoy14 approved these changes

2021-02-17 07:56 UTC, GingerBoy14 commented on src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
> +  //type: PropTypes.oneOf(Object.keys(productTypeMap)).isRequired
If u don't use it - remove

2021-02-17 09:10 UTC, okrdima approved these changes

2021-02-17 09:10 UTC, merged